# Generated by Django 3.0 on 2021-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_admin_data',
            name='Expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='st_admin_data',
            name='Issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
